<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The Muqaddimah An Introduction to Hist_33a059</name>
   <tag></tag>
   <elementGuidId>555f73f4-064d-4207-a0d4-6af221da8278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#productTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='productTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#productTitle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd8b02dc-3555-4fa5-baa9-b68ead47ef30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productTitle</value>
      <webElementGuid>c2583464-ba36-44d5-ae91-63775633634f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-extra-large celwidget</value>
      <webElementGuid>fa3af15c-8101-4321-8f28-fed00ab7921e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>hr6rxy-izv9me-r1qipj-sww293</value>
      <webElementGuid>de246b9a-b54c-4bea-8ecc-fcbce9fa63af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cel-widget</name>
      <type>Main</type>
      <value>productTitle</value>
      <webElementGuid>7368ff33-2930-4451-ae41-6fd0648cb240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  The Muqaddimah: An Introduction to History - Abridged Edition (Princeton Classics, 13) </value>
      <webElementGuid>15bc571e-7963-4200-8cf9-45b8086d2a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productTitle&quot;)</value>
      <webElementGuid>b7ef67fa-3552-44b0-9e1c-44b1c12a444d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='productTitle']</value>
      <webElementGuid>fd8fa7aa-d98e-4fd8-9904-85d90bc66dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='title']/span</value>
      <webElementGuid>70c15236-a7b3-47c4-bf26-63c2e175a97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Something went wrong. Please try your request again later.'])[1]/following::span[6]</value>
      <webElementGuid>f89e28fc-9320-479c-a08d-4c603b8cf8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[1]/following::span[7]</value>
      <webElementGuid>bfbdf04a-354f-408f-a2cb-f07e171eefe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paperback – Abridged, April 27, 2015'])[1]/preceding::span[1]</value>
      <webElementGuid>77c45de1-dd16-4f76-975f-9cac01328c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Muqaddimah: An Introduction to History - Abridged Edition (Princeton Classics, 13)']/parent::*</value>
      <webElementGuid>2994ad5b-d2f9-451b-8f92-aee8c41becdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>127655dd-7f68-4b0c-a775-7fd03fa9d07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'productTitle' and (text() = '  The Muqaddimah: An Introduction to History - Abridged Edition (Princeton Classics, 13) ' or . = '  The Muqaddimah: An Introduction to History - Abridged Edition (Princeton Classics, 13) ')]</value>
      <webElementGuid>942055a8-f8e5-4248-8faf-16dfa8b85419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
